Composer install after pull
greeflas/git-hooks pull request #3
Opened 2019-05-08 22:07 UTC by maxim-kravets

I added script that run installation of composer packages after pull or merge. Check, please.

2019-05-09 08:13 UTC, greeflas requested changes

2019-05-09 08:13 UTC, greeflas commented on README.md
> +composer.json after pull or
Please add: composer.json or composer.lock if it presents after...

2019-05-09 08:13 UTC, greeflas commented on src/pre-commit/php_cs_fixer.sh
> +git add --all
It seems this changes comes from previous PR :) Please, rebase with master branch.

2019-05-09 08:13 UTC, greeflas commented on src/post-merge/composer_install.sh
> +composer -v > /dev/null 2>&1
Is better to check that command exists

```suggestion
command -v composer > /dev/null 2>&1
```

2019-05-09 08:13 UTC, greeflas commented on src/post-merge/composer_install.sh
> +if [[ $COMPOSER -ne 0 ]]; then
Please move `then` keyword to the next line regarding project code style

2019-05-09 21:33 UTC, maxim-kravets commented
@greeflas i did all requested changes.

2019-05-10 07:34 UTC, merged

2019-05-10 07:34 UTC, greeflas commented
@maxim-kravets Thanks for contributing!